from .basicvsr_model import basicVSR
from .basicvsrpp_model import BasicVSRPlusPlus
from .basicvsrattention_model import BasicVSRWithAttention
from .multistagebasicvsr_model import MultiStageBasicVSR
from .multistagebasicvsr_model_analysis import MultiStageBasicVSRAnalysis
from .multistagebasicvsr_model_bn import MultiStageBasicVSRBN
from .multistagebasicvsr_model_mhead import MultiStageBasicMhead
# from .iconvsr_model import iconVSR